networks:
  rustdesk-net:
    external: false

services:
  hbbs:
    container_name: rustdesk_hhbs
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118
    image: rustdesk/rustdesk-server
    command: hbbs -r yourname.synology.me:21117
    volumes:
      - ${APPDATA_LOCATION}/rustdeskhbbs:/root:rw
    networks:
      - rustdesk-net
    depends_on:
      - hbbr
    restart: on-failure:5

  hbbr:
    container_name: rustdesk_hbbr
    ports:
      - 21117:21117
      - 21119:21119
    image: rustdesk/rustdesk-server
    command: hbbr
    volumes:
      - ${APPDATA_LOCATION}/rustdeskhbbr:/root:rw
    networks:
      - rustdesk-net
    restart: on-failure:5