services:
  navidrome:
    image: deluan/navidrome:0.63.2
    user: ${PUID}:${PGID}
    ports:
      - 26856:4533
    restart: unless-stopped
    volumes:
      - ${APPDATA_LOCATION}/navidrome:/data
      - ${MEDIA_LOCATION}/music:/music:ro
