services:
  syncthing:
    image: syncthing/syncthing:2.0.8
    container_name: syncthing
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - data:/var/syncthing:rw
    restart: unless-stopped
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3

volumes:
  data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${APPDATA_LOCATION}/syncthing