---
# =====================================================================
# Cleanup Desktop
# =====================================================================
- name: Get Public shortcuts.
  ansible.windows.win_find:
    paths:
      - 'C:\Users\Public\Desktop'
    patterns: 
      - "*.lnk"
      - "*.url"
  register: public_shortcuts
  changed_when: false
  check_mode: false
  
- name: Remove Public shortcuts from the Desktop.
  ansible.windows.win_file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ public_shortcuts.files | unique }}"
  when: public_shortcuts.files | length > 0

- include_tasks: user_desktop_cleanup.yml
  vars:
    user: "{{ current_user.username }}"
  loop: "{{ users }}"
  loop_control:
    loop_var: current_user


# =====================================================================
# Update Windows
# =====================================================================
- name: Check for missing updates.
  ansible.windows.win_updates:
    state: searched

- name: Install Windows updates.
  ansible.windows.win_updates:
    category_names: "{{ update_categories | default(omit) }}"
    reboot: "{{ windows_updates_reboot | default(false) }}"
  register: update_result
  until: update_result.found_update_count == 0
