services:
  actual_server:
    image: actualbudget/actual-server:25.8.0
    container_name: actual_budget
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/5006' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    ports:
      - ${EXPOSE_PORT}:5006
    volumes:
      - ${APPDATA_LOCATION}:/data:rw
    restart: on-failure:5