services:
  broker:
    image: docker.io/valkey/valkey:9-alpine
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/postgres:18
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:3.0.5
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - "13068:8000"
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_DBENGINE: postgresql
      PAPERLESS_SECRET_KEY: ${SECRET_KEY}
      USERMAP_UID: ${PUID}
      USERMAP_GID: ${PGID}


volumes:
  data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${APPDATA_LOCATION}/paperless/data
  media:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${APPDATA_LOCATION}/paperless/media
  pgdata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${APPDATA_LOCATION}/paperless/pgdata
  redisdata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${APPDATA_LOCATION}/paperless/redisdata