services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:1.42.2.10156-f737b826c
    restart: unless-stopped
    environment:
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
      - TZ=${TZ}
    network_mode: host
    volumes:
      - ${APPDATA_LOCATION}/plex/config:/config
      - ${MEDIA_LOCATION}:/data
      - /dev/shm/plex/transcode:/transcode
    deploy:
     resources:
       reservations:
         devices:
           - driver: nvidia
             count: 1
             capabilities: [gpu]