---
- name: Configure Hermes
  hosts: hermes
  gather_facts: true

  roles:
  - role: system/windows_base
    vars:
      hostname: Hermes
      users_to_rename:
      - old_username: 'astyv'
        new_username: 'andrew'